spring:
  application:
    name: readerprint-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    url: jdbc:mysql://localhost:3306/myapp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    password: mypass
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 3YinZSAuNUWlIKhiIh7Lo0EZwWZspLv0
  expiration: '1800000'
  refresh-expiration: '604800000'

logging:
  level:
    org:
      hibernate:
        SQL: INFO
    p6spy: INFO


# 국립중앙도서관
nl:
  api:
    base-url: https://www.nl.go.kr/NL/search/openApi/search.do
    key: bf2cda60113124bef54058dcd457633a346166d5a08aad19d4d633621941fdba